include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
    prefer_const_constructors: ignore # delete this at the end and add all the consts
    todo: info
    prefer_if_elements_to_conditional_expressions: ignore
    prefer_conditional_assignment: info
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"